UNIQUE_CONSTRAINTS = {
    "Employee": "id",
    "Department": "id",
    "Role": "id",
    "Supplier": "id",
    "Customer": "id",
    "Product": "id",
    "Document": "id",
    "DocumentVersion": "id",
    "Section": "id",
    "Chunk": "id",
    "Organization": "id",
    "Department": "id",
    "Role": "id",
    "Location": "id",
    "Product": "id",
    "Contract": "id",
    "PurchaseOrder": "id",
    "SalesOrder": "id",
    "Invoice": "id",
    "Payment": "id",
    "Rule": "id",
    "Condition": "id",
    "DataSource": "id",
    "SourceRecord": "id",
    "IngestionJob": "id",
    "Skill": "normalized_name",
}
