import hashlib
from pathlib import Path

from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings

from app.retrieval.employee_vector_store import DEFAULT_EMBEDDING_MODEL


class PolicyVectorStore:
    """Persist policy chunks in a local FAISS index with source metadata."""

    def __init__(
        self,
        index_path: str | Path,
        embedding_model: str = DEFAULT_EMBEDDING_MODEL,
    ):
        self.index_path = Path(index_path)
        self.embedding_model = embedding_model
        self._embeddings: HuggingFaceEmbeddings | None = None
        self._store: FAISS | None = None

    @property
    def embeddings(self) -> HuggingFaceEmbeddings:
        if self._embeddings is None:
            self._embeddings = HuggingFaceEmbeddings(model_name=self.embedding_model)
        return self._embeddings

    def replace_source(self, chunks: list[Document]) -> None:
        """Replace every chunk for one source document, avoiding stale evidence."""
        if not chunks:
            return

        source_id = chunks[0].metadata["source_id"]
        source_name = chunks[0].metadata["source_document"]
        store = self._load()

        if store is None:
            self._store = FAISS.from_documents(
                chunks,
                self.embeddings,
                ids=[self._document_id(chunk) for chunk in chunks],
            )
        else:
            stored_ids = [
                document_id
                for document_id, document in store.docstore._dict.items()
                if document.metadata.get("source_id") == source_id
                or (
                    document.metadata.get("source_id") is None
                    and document.metadata.get("source_document") == source_name
                )
            ]
            if stored_ids:
                store.delete(stored_ids)
            store.add_documents(
                chunks,
                ids=[self._document_id(chunk) for chunk in chunks],
            )

        self.index_path.mkdir(parents=True, exist_ok=True)
        self._store.save_local(str(self.index_path))

    def search_with_scores(
        self, query: str, limit: int = 5
    ) -> list[tuple[Document, float]]:
        store = self._load()
        if store is None:
            return []
        return store.similarity_search_with_score(query, k=limit)

    def _load(self) -> FAISS | None:
        if self._store is not None:
            return self._store
        if not (self.index_path / "index.faiss").exists():
            return None

        # This index is generated by this application. Do not load untrusted indexes.
        self._store = FAISS.load_local(
            str(self.index_path),
            self.embeddings,
            allow_dangerous_deserialization=True,
        )
        return self._store

    @staticmethod
    def _document_id(chunk: Document) -> str:
        identity = "|".join(
            [
                chunk.metadata["source_id"],
                str(chunk.metadata["page"]),
                chunk.metadata["section"],
                str(chunk.metadata["chunk_number"]),
                chunk.page_content,
            ]
        )
        return hashlib.sha256(identity.encode("utf-8")).hexdigest()
